"paragraphUniqueId": bfdde1ba-501c-450b-a37b-a4129615b138
"sourceParagraphId": 21840
"sortOrder": 41
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "29d6b442-6011-4315-9d5c-326759221023"
  "Height": "32"
  "Id": "713"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
