"id": 3396b8f2-dc94-41f7-924a-17cd56dcf5d9
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"topSpacing": 6
"bottomSpacing": 6
"verticalAlignment": "None"
"columns":
- "id": 1
  "width": 0
