"paragraphUniqueId": 6c52b108-fcb1-4259-84ab-6be0156a8872
"sourceParagraphId": 161
"sortOrder": 8
"itemType": "Swift-v2_ProductListNavigation"
"header": "T"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "781e72d3-f8f2-4927-bf6f-7764a4276ba6"
  "GroupNavigationLayout": "filter"
  "GroupNavigationStartLevel": "1"
  "GroupNavigationStopLevel": "9"
  "Id": "2"
  "ItemInstanceType": ""
  "Sort": 0
  "Title": ""
"columnId": 1
