"paragraphUniqueId": 44e36d33-daf5-4ae7-8d3e-9cf43efb1def
"sourceParagraphId": 5600
"sortOrder": 4
"itemType": "Swift-v2_Accordion"
"header": "Accordion"
"template": "Shadow.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Accordion_Items": 5
  "GlobalRecordPageGuid": "a8ff170e-57d1-4837-ba2e-b90fa6ed6c32"
  "Id": "3"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
