"paragraphUniqueId": 94345aa0-5897-44c2-b15a-ccb4ac80cb73
"sourceParagraphId": 154
"sortOrder": 6
"itemType": "Swift-v2_BreadcrumbNavigation"
"header": "Breadcrumb navigation"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "95d9d67a-d324-444e-912e-bd36e5eb96f7"
  "Id": "3"
  "ItemInstanceType": ""
  "ShowProductInBreadcrumb": true
  "Sort": 0
"columnId": 1
