"id": 01b90000-01d0-4407-8225-2d62b31fef86
"sortOrder": 26
"definitionId": "1ColumnEmail"
"itemType": "Swift-v2_EmailRow"
"container": "Grid"
"colorSchemeId": "dark"
"verticalAlignment": "None"
"fields":
  "Id": "584"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
