"paragraphUniqueId": 490ebae3-f66d-4e3d-a0ca-970f31824be6
"sourceParagraphId": 145
"sortOrder": 4
"itemType": "Swift-v2_ProductListFacets"
"header": "Facets"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "EnableGroupNavigation": false
  "ExpandFacetGroups": "all"
  "GlobalRecordPageGuid": "75f66146-aab9-4d82-b57b-0b5d6094524f"
  "GroupNavigationStartLevel": "2"
  "GroupNavigationStopLevel": "9"
  "Id": "2"
  "ItemInstanceType": ""
  "Layout": "horizontal"
  "Sort": 0
  "SortByHighestPrice": false
  "SortByLowestPrice": false
  "SortByMostSold": false
  "SortByNameAZ": true
  "SortByNameZA": true
  "SortByNewest": false
  "SortByRelevance": true
  "Title": ""
"columnId": 1
