"paragraphUniqueId": b87a19b8-5d91-42f7-b6dd-253579255d4d
"sourceParagraphId": 22157
"sortOrder": 20
"itemType": "Swift-v2_Accordion"
"header": "Accordion"
"template": "Shadow.cshtml"
"colorSchemeId": "light"
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Accordion_Items": 394
  "GlobalRecordPageGuid": "5c47a52a-4a24-449e-8df9-563f03afe297"
  "Id": "120"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
