"OrderStateId": "OS10"
"OrderStateName": "Draft"
"OrderStateDescription": ""
"OrderStateIsDefault": true
"OrderStateDontUseInstatistics": false
"OrderStateIsDeleted": false
"OrderStateMailTemplate": ""
"OrderFlowId": 4
"OrderStateMailSender": ""
"OrderStateMailSenderName": ""
"OrderStateMailSubject": ""
"OrderStateAutoId": 10
"OrderStateSendToCustomer": false
"OrderStateOthersMailTemplate": ""
"OrderStateOthersRecipients": ""
"OrderStateSortOrder": 0
"OrderStateOrderType": 3
"OrderStateAllowOrder": false
"OrderStateSendToDeliveryEmail": false
"OrderStateSendToField": false
"OrderStateCustomRecipientField": ""
"OrderStateAllowEdit": false
"OrderStateColor": "#bfbfbf"
