"OrderStateId": "OS13"
"OrderStateName": "Paid"
"OrderStateDescription": ""
"OrderStateIsDefault": false
"OrderStateDontUseInstatistics": false
"OrderStateIsDeleted": false
"OrderStateMailTemplate": ""
"OrderFlowId": 4
"OrderStateMailSender": ""
"OrderStateMailSenderName": ""
"OrderStateMailSubject": ""
"OrderStateAutoId": 13
"OrderStateSendToCustomer": false
"OrderStateOthersMailTemplate": ""
"OrderStateOthersRecipients": ""
"OrderStateSortOrder": 3
"OrderStateOrderType": 3
"OrderStateAllowOrder": false
"OrderStateSendToDeliveryEmail": false
"OrderStateSendToField": false
"OrderStateCustomRecipientField": ""
"OrderStateAllowEdit": false
"OrderStateColor": "#10B981"
