"OrderStateId": "OS7"
"OrderStateName": "Rejected"
"OrderStateDescription": ""
"OrderStateIsDefault": false
"OrderStateDontUseInstatistics": false
"OrderStateIsDeleted": false
"OrderStateMailTemplate": ""
"OrderFlowId": 2
"OrderStateMailSender": ""
"OrderStateMailSenderName": ""
"OrderStateMailSubject": ""
"OrderStateAutoId": 7
"OrderStateSendToCustomer": false
"OrderStateOthersMailTemplate": ""
"OrderStateOthersRecipients": ""
"OrderStateSortOrder": 0
"OrderStateOrderType": 4
"OrderStateAllowOrder": false
"OrderStateSendToDeliveryEmail": false
"OrderStateSendToField": false
"OrderStateCustomRecipientField": ""
"OrderStateAllowEdit": false
"OrderStateColor": "#cf2a2a"
