"paragraphUniqueId": aea645f5-f907-4a07-a9a9-8f4614803569
"sourceParagraphId": 146
"sortOrder": 2
"itemType": "Swift-v2_ProductListItemRepeater"
"header": "Product component repeater"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "75f66146-aab9-4d82-b57b-0b5d6094524f"
  "GridLayoutDesktop": "4-columns"
  "GridLayoutMobile": "list"
  "HideNoProductsFoundMessage": false
  "Id": "2"
  "ItemInstanceType": ""
  "ListComponentSource": "39"
  "NoProductsFoundMessage": ""
  "Sort": 0
  "Title": ""
"columnId": 1
