"id": be3ab42b-b266-48f6-a739-074d08b62868
"sortOrder": 12
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 3
"topSpacing": 0
"bottomSpacing": 0
"verticalAlignment": "None"
"fields":
  "Id": "932"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
