"paragraphUniqueId": e59b3594-e154-49b8-8fbb-84e1b24b23a8
"sourceParagraphId": 22154
"sortOrder": 17
"itemType": "Swift-v2_PostList"
"header": ""
"template": "PostSlider.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "5c47a52a-4a24-449e-8df9-563f03afe297"
  "Id": "5"
  "ItemInstanceType": ""
  "ParentPage": "8366"
  "Sort": 0
"columnId": 1
