"id": ecd71702-8e57-430f-abdf-3037f0d679a3
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"topSpacing": 4
"bottomSpacing": 2
"verticalAlignment": "None"
"columns":
- "id": 1
  "width": 0
