"paragraphUniqueId": ff7a2891-cfe5-43ec-97ef-b6eb6c4365bc
"sourceParagraphId": 20204
"sortOrder": 6
"itemType": "Swift-v2_BreadcrumbNavigation"
"header": "Breadcrumb navigation"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "15e4ab2a-a10e-4959-8c9f-67293f8afa30"
  "Id": "120"
  "ItemInstanceType": ""
  "ShowProductInBreadcrumb": true
  "Sort": 0
"columnId": 1
