"id": 345748dc-6071-4159-91e7-c9e01770ceab
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"topSpacing": 6
"bottomSpacing": 3
"gapX": 3
"gapY": 3
"mobileLayout": "12,12,12"
"verticalAlignment": "Start"
"fields":
  "Id": "128"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
