"paragraphUniqueId": 672eb7e5-8e3e-44c0-8442-9e05e424b605
"sourceParagraphId": 21941
"sortOrder": 35
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "4081a661-c987-4804-897d-5a1a6b500f10"
  "Height": "32"
  "Id": "777"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
