"id": cff9769a-f7e1-4390-8dc5-b8d66d9d9fc0
"sortOrder": 3
"definitionId": "1ColumnEmail"
"itemType": "Swift-v2_EmailRow"
"container": "Grid"
"verticalAlignment": "None"
"fields":
  "Id": "483"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
