"paragraphUniqueId": b1892e95-6737-477b-ad35-9dec440538e6
"sourceParagraphId": 105
"sortOrder": 1
"itemType": "Swift-v2_App"
"header": "(EMPTY)"
"template": ""
"colorSchemeId": ""
"moduleSystemName": "UserView"
"moduleSettings": |-
  <?xml version="1.0" encoding="utf-8"?>
  <Settings>
    <ListTemplate></ListTemplate>
    <DetailTemplate>UserDetail.cshtml</DetailTemplate>
    <Source>CurrentUser</Source>
    <ChosenUser></ChosenUser>
    <ListUsers></ListUsers>
    <ListUserGroups></ListUserGroups>
    <ShowInactiveUsers>0</ShowInactiveUsers>
    <PageSize>10</PageSize>
    <SortBy>Id</SortBy>
    <SortOrder>Ascending</SortOrder>
    <EmailTemplate></EmailTemplate>
    <EditUserPageId>Default.aspx?ID=96</EditUserPageId>
    <CreateUserPageId></CreateUserPageId>
    <CreatePasswordPageId></CreatePasswordPageId>
  </Settings>
"fields":
  "GlobalRecordPageGuid": "4d5fd10f-3af1-4422-a6a3-65ef8ba94903"
  "Id": "42"
  "ItemInstanceType": ""
  "Sort": 0
  "Title": ""
"columnId": 1
