"paragraphUniqueId": 3407c742-9ccd-4f75-85ba-914c11d367f4
"sourceParagraphId": 8864
"sortOrder": 9
"itemType": "Swift-v2_EmailHeading"
"header": "Items ordered"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "24"
  "GlobalRecordPageGuid": "29d6b442-6011-4315-9d5c-326759221023"
  "Id": "137"
  "ItemInstanceType": ""
  "LineHeight": "1"
  "Padding": "16"
  "Sort": 0
  "Title": "Items ordered"
"columnId": 1
