"id": 04fac2f2-b671-4a7d-99ef-0659ad016238
"sortOrder": 3
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"topSpacing": 0
"bottomSpacing": 6
"verticalAlignment": "None"
"fields":
  "Id": "721"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
