"paragraphUniqueId": a827eac1-7c87-4967-8044-5656d9b905e4
"sourceParagraphId": 22147
"sortOrder": 10
"itemType": "Swift-v2_Image"
"header": ""
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "AltText": ""
  "GlobalRecordPageGuid": "5c47a52a-4a24-449e-8df9-563f03afe297"
  "Id": "1097"
  "Image": ""
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
