"id": a4e32595-f8b9-47bb-8a61-8b7237b3c0f2
"sortOrder": 5
"definitionId": "1ColumnEmail"
"itemType": "Swift-v2_EmailRow"
"container": "Grid"
"verticalAlignment": "None"
"fields":
  "Id": "602"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
