"paragraphUniqueId": 2963cc01-9b46-4950-bc75-7abdebf50a7a
"sourceParagraphId": 20170
"sortOrder": 3
"itemType": "Swift-v2_Text"
"header": "Terms and conditions"
"template": "TextLeft.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "51e253d5-77ff-40b2-a92f-498ae0521b10"
  "Id": "1181"
  "ItemInstanceType": ""
  "Sort": 0
  "Subtitle": ""
  "Text": ""
  "Title": "<h1 class=\"dw-h2\">Terms and conditions</h1>"
"columnId": 1
