"id": 1f662601-0fa8-41e6-a8b1-66c455e2fb15
"sortOrder": 3
"definitionId": "1ColumnEmail"
"itemType": "Swift-v2_EmailRow"
"container": "Grid"
"verticalAlignment": "None"
"fields":
  "Id": "520"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
