"paragraphUniqueId": 114c0c07-d88e-45e0-b087-16998fe20308
"sourceParagraphId": 21858
"sortOrder": 7
"itemType": "Swift-v2_EmailHeading"
"header": "By Dynamicweb"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "16"
  "GlobalRecordPageGuid": "a65aa8c9-49a7-4013-94a3-751eef5aafa3"
  "Id": "424"
  "ItemInstanceType": ""
  "LineHeight": "1.5"
  "Padding": "0"
  "Sort": 0
  "Title": "By Dynamicweb"
"columnId": 1
