"paragraphUniqueId": 5bf19890-c97b-4ee5-8932-0bf4b27f6f03
"sourceParagraphId": 21726
"sortOrder": 37
"itemType": "Swift-v2_EmailImage"
"header": ""
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "961323a5-86f4-4b70-9eb8-191f1aa054a6"
  "Id": "134"
  "Image": "/Files/Images/Products/Bikes/Merida/Details/BIG-NINE/65A9677.jpg"
  "ImageAltText": ""
  "ItemInstanceType": ""
  "LinkType": "page"
  "Padding": "16"
  "PageLink": ""
  "ProductGroupLink": ""
  "ProductLink": ""
  "Sort": 0
"columnId": 2
