"paragraphUniqueId": 58ec3c64-221b-49be-8053-52e8fcb07b5d
"sourceParagraphId": 176
"sortOrder": 1
"itemType": "Swift-v2_App"
"header": "App"
"template": ""
"colorSchemeId": ""
"moduleSystemName": "UserAuthentication"
"moduleSettings": |-
  <?xml version="1.0" encoding="utf-8"?>
  <Settings>
    <LoginTemplate>Login.cshtml</LoginTemplate>
    <RedirectToSpecificPage>Default.aspx?ID=99</RedirectToSpecificPage>
    <RedirectToReferrer>0</RedirectToReferrer>
    <CreatePasswordPageId>Default.aspx?ID=139</CreatePasswordPageId>
    <CreateUserPageId>Default.aspx?ID=136</CreateUserPageId>
    <ListUserProfiles>0</ListUserProfiles>
    <UserProfilesTemplate></UserProfilesTemplate>
    <OneTimeCodeTemplate></OneTimeCodeTemplate>
    <MagicLinkTemplate></MagicLinkTemplate>
  </Settings>
"fields":
  "GlobalRecordPageGuid": "37f77e12-1947-4dd2-89ae-8319697016a4"
  "Id": "52"
  "ItemInstanceType": ""
  "Sort": 0
  "Title": "App"
"columnId": 1
