"pageUniqueId": 5c8b1c35-d4ca-4ac2-b4de-48ac88c8aa08
"sourcePageId": 1688
"name": "Search result page"
"menuText": "Search result page"
"sortOrder": 4
"isActive": false
"itemType": "Swift-v2_Page"
"layoutApplyToSubPages": false
"isFolder": false
"treeSection": "Swift Setup"
"navigationTag": "ContentSearch"
"hidden": false
"allowclick": true
"allowsearch": false
"showInSitemap": true
"showInLegend": true
"sslMode": 0
"displayMode": "Normal"
"activeFrom": 2022-08-22T11:09:00.0000000
"activeTo": 2999-12-31T23:59:59.0000000
"permissionType": 2
"seo":
  "noindex": true
  "nofollow": true
  "robots404": false
"urlSettings":
  "urlIgnoreForChildren": false
  "urlUseAsWritten": false
"visibility":
  "hideForPhones": false
  "hideForTablets": false
  "hideForDesktops": false
"fields":
  "Id": "636"
  "ItemInstanceType": ""
  "Sort": 4
  "Title": "Search result page"
"propertyFields":
  "Id": "967"
  "Sort": 0
  "ItemInstanceType": ""
  "Icon": "/Files/Icons/1_none.svg"
  "SubmenuType": "auto"
