"ShippingId": "SHIP8"
"ShippingLanguageId": "ENU"
"ShippingName": "DAO"
"ShippingDescription": ""
"ShippingPriceOverMaxWeight": 0
"ShippingFreeFeeAmount": 0
"ShippingServiceSystemName": ""
"ShippingServiceParameters": ""
"ShippingSorting": 9
"ShippingFeeSelection": "high"
"ShippingIcon": ""
"ShippingLimitsUseLogic": 1
"ShippingFeeRulesSource": 2
"ShippingTakeDiscountIntoAccount": true
"ShippingEligibleForFreeShipping": false
"ShippingActive": false
"ShippingUserGroups": ""
"ShippingAllowAnonymousUsers": false
"ShippingCode": ""
"ShippingAgentCode": ""
"ShippingAgentName": ""
"ShippingAgentServiceCode": ""
"ShippingAgentServiceDescription": ""
"ShippingUsePriceWithVat": false
"ShippingMinWeight": 
"ShippingMaxWeight": 
"ShippingProductIds": ""
"ShippingProductGroupIds": ""
"ShippingProductFilterMode": 0
