"paragraphUniqueId": 66900f02-aec8-48a5-931f-4d342c9f8f2a
"sourceParagraphId": 7667
"sortOrder": 8
"itemType": "Swift-v2_EmailHeading"
"header": "Lightweight & comfortable"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "44"
  "GlobalRecordPageGuid": "961323a5-86f4-4b70-9eb8-191f1aa054a6"
  "Id": "99"
  "ItemInstanceType": ""
  "LineHeight": "1.25"
  "Padding": "48"
  "Sort": 0
  "Title": "Lightweight & comfortable"
"columnId": 1
