"paragraphUniqueId": 8d438338-1b8a-4644-b696-a72878bd68e0
"sourceParagraphId": 22141
"sortOrder": 4
"itemType": "Swift-v2_Image"
"header": ""
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "AltText": ""
  "GlobalRecordPageGuid": "5c47a52a-4a24-449e-8df9-563f03afe297"
  "Id": "1096"
  "Image": "/Files/Images/Content/Details/details-8.jpg?x=0&y=-3&r=16/9"
  "ItemInstanceType": ""
  "Link": ""
  "Sort": 0
"columnId": 1
