"id": a4a5dc9b-974d-497f-abc6-4c2bc16f6e1f
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"topSpacing": 6
"bottomSpacing": 6
"verticalAlignment": "None"
"fields":
  "Id": "719"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
