"id": 6a2787f6-8340-4dd6-a310-694441152031
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 3
"topSpacing": 3
"bottomSpacing": 6
"verticalAlignment": "None"
"columns":
- "id": 1
  "width": 0
