"paragraphUniqueId": 19aa6a25-2ae9-47d2-aeda-687975bc14d1
"sourceParagraphId": 138
"sortOrder": 13
"itemType": "Swift-v2_Text"
"header": "Sales"
"template": "TextCenter.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "FirstButton": "{\r\n  \"SelectedValue\": \"\",\r\n  \"Label\": \"\",\r\n  \"Link\": \"\",\r\n  \"LinkType\": \"\",\r\n  \"Style\": \"primary\"\r\n}"
  "GlobalRecordPageGuid": "52cb5376-fddd-48fa-9b65-6e345bec1fd0"
  "Id": "31"
  "ItemInstanceType": ""
  "SecondButton": "{\r\n  \"SelectedValue\": \"\",\r\n  \"Label\": \"\",\r\n  \"Link\": \"\",\r\n  \"LinkType\": \"\",\r\n  \"Style\": \"primary\"\r\n}"
  "Sort": 0
  "Subtitle": "<h3 class=\"dw-h3\">1m+</h3>"
  "Title": "<p class=\"dw-paragraph-1\">Sales"
"columnId": 2
