"paragraphUniqueId": dd874888-b4ba-4911-a4aa-aacf68348d66
"sourceParagraphId": 139
"sortOrder": 14
"itemType": "Swift-v2_Text"
"header": "Feedback"
"template": "TextCenter.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "FirstButton": "{\r\n  \"SelectedValue\": \"\",\r\n  \"Label\": \"\",\r\n  \"Link\": \"\",\r\n  \"LinkType\": \"\",\r\n  \"Style\": \"primary\"\r\n}"
  "GlobalRecordPageGuid": "52cb5376-fddd-48fa-9b65-6e345bec1fd0"
  "Id": "32"
  "ItemInstanceType": ""
  "SecondButton": "{\r\n  \"SelectedValue\": \"\",\r\n  \"Label\": \"\",\r\n  \"Link\": \"\",\r\n  \"LinkType\": \"\",\r\n  \"Style\": \"primary\"\r\n}"
  "Sort": 0
  "Subtitle": "<h3 class=\"dw-h3\">300+</h3>"
  "Title": "<p class=\"dw-paragraph-1\">Feedback"
"columnId": 3
