"id": 49f4361b-8973-4f75-8174-c871d241c3b5
"sortOrder": 3
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"topSpacing": 0
"bottomSpacing": 0
"verticalAlignment": "None"
"fields":
  "Id": "115"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
