"paragraphUniqueId": 6abaab3e-56b6-4878-ba7b-98f74b27da3d
"sourceParagraphId": 22150
"sortOrder": 13
"itemType": "Swift-v2_Text"
"header": "Sales"
"template": "TextCenter.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "FirstButton": "{\r\n  \"SelectedValue\": \"\",\r\n  \"Label\": \"\",\r\n  \"Link\": \"\",\r\n  \"LinkType\": \"\",\r\n  \"Style\": \"primary\"\r\n}"
  "GlobalRecordPageGuid": "5c47a52a-4a24-449e-8df9-563f03afe297"
  "Id": "1428"
  "ItemInstanceType": ""
  "SecondButton": "{\r\n  \"SelectedValue\": \"\",\r\n  \"Label\": \"\",\r\n  \"Link\": \"\",\r\n  \"LinkType\": \"\",\r\n  \"Style\": \"primary\"\r\n}"
  "Sort": 0
  "Subtitle": "<h3 class=\"dw-h3\">1m+</h3>"
  "Title": "<p class=\"dw-paragraph-1\">Sales"
"columnId": 2
