"paragraphUniqueId": 4ab46b0a-9729-4d12-8b4e-d9e3aec4090f
"sourceParagraphId": 21916
"sortOrder": 43
"itemType": "Swift-v2_EmailHeading"
"header": "By Dynamicweb"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "12"
  "GlobalRecordPageGuid": "961323a5-86f4-4b70-9eb8-191f1aa054a6"
  "Id": "436"
  "ItemInstanceType": ""
  "LineHeight": "1.5"
  "Padding": "0"
  "Sort": 0
  "Title": "By Dynamicweb"
"columnId": 1
