"pageUniqueId": 4d5fd10f-3af1-4422-a6a3-65ef8ba94903
"sourcePageId": 95
"name": "My profile"
"menuText": "My profile"
"sortOrder": 6
"isActive": true
"itemType": "Swift-v2_Page"
"layoutApplyToSubPages": false
"isFolder": false
"isTemplate": false
"isStructuralStub": false
"navigationTag": "ViewProfile"
"hidden": false
"allowclick": true
"allowsearch": true
"showInSitemap": true
"showInLegend": true
"sslMode": 0
"displayMode": "Normal"
"activeFrom": 2026-01-08T12:23:00.0000000
"activeTo": 2999-12-31T23:59:59.0000000
"permissionType": 2
"masterPageGuid": 8b44ae04-1bf4-4d3d-8c64-a78684ce7105
"masterType": "None"
"seo":
  "noindex": false
  "nofollow": false
  "robots404": false
"urlSettings":
  "urlIgnoreForChildren": false
  "urlUseAsWritten": false
"visibility":
  "hideForPhones": false
  "hideForTablets": false
  "hideForDesktops": false
"fields":
  "Id": "60"
  "ItemInstanceType": ""
  "Sort": 1
  "Title": "Cruising the Boardwalks of Santa Monica on the Nirve Forty-Nine"
"propertyFields":
  "Id": "95"
  "Sort": 0
  "ItemInstanceType": ""
  "Icon": "/Files/Images/Icons/user.svg"
  "SubmenuType": "auto"
