"paragraphUniqueId": e9dfc9cb-8177-4a10-86b7-657f7084f511
"sourceParagraphId": 21842
"sortOrder": 43
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "29d6b442-6011-4315-9d5c-326759221023"
  "Height": "32"
  "Id": "714"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
