"CountryCode2": "AT"
"CountryCode3": "AUT"
"CountryCurrencyCode": "EUR"
"CountryNumber": "14"
"CountryVAT": 20
"CountryCultureInfo": "at"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
