"CountryCode2": "CA"
"CountryCode3": ""
"CountryCurrencyCode": ""
"CountryNumber": "0"
"CountryVAT": 0
"CountryCultureInfo": ""
"CountryRegionCode": "NB"
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
