"CountryCode2": "CY"
"CountryCode3": "CYP"
"CountryCurrencyCode": "EUR"
"CountryNumber": "59"
"CountryVAT": 19
"CountryCultureInfo": "cy"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
