"CountryCode2": "DK"
"CountryCode3": "DNK"
"CountryCurrencyCode": "DKK"
"CountryNumber": "208"
"CountryVAT": 25
"CountryCultureInfo": "da-DK"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": ""
