"CountryCode2": "ES"
"CountryCode3": "ESP"
"CountryCurrencyCode": "EUR"
"CountryNumber": "217"
"CountryVAT": 21
"CountryCultureInfo": "es"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
