"CountryCode2": "IE"
"CountryCode3": "IRL"
"CountryCurrencyCode": "EUR"
"CountryNumber": "68"
"CountryVAT": 23
"CountryCultureInfo": "ie"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
