"CountryCode2": "PL"
"CountryCode3": "POL"
"CountryCurrencyCode": "PLN"
"CountryNumber": "191"
"CountryVAT": 23
"CountryCultureInfo": "pl"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
