"CountryCode2": "PT"
"CountryCode3": "PRT"
"CountryCurrencyCode": "EUR"
"CountryNumber": "193"
"CountryVAT": 23
"CountryCultureInfo": "pt"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
