"CountryCode2": "SK"
"CountryCode3": "SVK"
"CountryCurrencyCode": "EUR"
"CountryNumber": "143"
"CountryVAT": 22
"CountryCultureInfo": "sk"
"CountryRegionCode": ""
"CountryAddressDisplayFormatMode": 1
"CountryAddressDisplayFormat": ""
"CountryAddressEditFormatMode": 1
"CountryAddressEditFormat": ""
"CountryReverseChargeForVAT": false
"CountryVatPostingGroup": 
