"id": 48d741f0-d579-4d6e-b41d-d94564dcf87f
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 4
"topSpacing": 0
"bottomSpacing": 0
"verticalAlignment": "None"
"fields":
  "Id": "921"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
