"paragraphUniqueId": 63f2050e-a55e-4195-b2d6-f2731eb66dc6
"sourceParagraphId": 113
"sortOrder": 5
"itemType": "Swift-v2_Image"
"header": "Share the fun"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "410d78fe-8690-40ee-aa5b-ede6f00bae7d"
  "Id": "5"
  "Image": "/Files/Images/eONE-FORTY_700_redblk_MY2021_EMBARGO-2020-09-01.jpg?x=14&y=-6"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
