"paragraphUniqueId": 8439cb86-a284-4673-80ca-10aa01c2b14d
"sourceParagraphId": 21929
"sortOrder": 32
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "4081a661-c987-4804-897d-5a1a6b500f10"
  "Height": "32"
  "Id": "770"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
