"paragraphUniqueId": fe0cb9fa-d9f6-477d-8254-6049ee1818bf
"sourceParagraphId": 21844
"sortOrder": 7
"itemType": "Swift-v2_EmailHeading"
"header": "Swift"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "40"
  "GlobalRecordPageGuid": "d64e3ca2-b3f8-43c6-af45-165daad9e16b"
  "Id": "419"
  "ItemInstanceType": ""
  "LineHeight": "1.5"
  "Padding": "0"
  "Sort": 0
  "Title": "Swift"
"columnId": 1
