"id": 57131d53-d11d-4cd7-bb17-c1926e22816a
"sortOrder": 3
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"topSpacing": 0
"bottomSpacing": 4
"verticalAlignment": "None"
"columns":
- "id": 1
  "width": 0
