"id": 3c282ed2-0328-4603-8d90-4caf87bf899c
"sortOrder": 5
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"colorSchemeId": "lightgrey1"
"topSpacing": 6
"bottomSpacing": 6
"verticalAlignment": "None"
"columns":
- "id": 1
  "width": 0
