"id": 1d450788-dfac-4a14-afbe-6bb79f681a55
"sortOrder": 4
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 3
"topSpacing": 0
"bottomSpacing": 6
"verticalAlignment": "None"
"fields":
  "Id": "116"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
