"MethodCountryRelCode2": "CREL64"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "NO"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3040
