"MethodCountryRelCode2": "CREL2976"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "LU"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2976
