"MethodCountryRelCode2": "CREL2991"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "DK"
"MethodCountryRelMethodId": "PAY3"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2991
