"MethodCountryRelCode2": "CREL2992"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "DK"
"MethodCountryRelMethodId": "SHIP13"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2992
