"MethodCountryRelCode2": "CREL65"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "PL"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3041
