"MethodCountryRelCode2": "CREL54"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "GR"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3030
