"MethodCountryRelCode2": "CREL49"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "CZ"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3025
