"MethodCountryRelCode2": "CREL2981"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "PT"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2981
