"MethodCountryRelCode2": "CREL2438"
"MethodCountryRelMethodType": "TAXSETTING"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "ID"
"MethodCountryRelAutoId": 2438
