"MethodCountryRelCode2": "CREL2958"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "AT"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2958
