"MethodCountryRelCode2": "CREL98"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "HU"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3074
