"MethodCountryRelCode2": "CREL2933"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "CZ"
"MethodCountryRelMethodId": "SHIP6"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2933
