"MethodCountryRelCode2": "CREL101"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "LV"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3077
