"MethodCountryRelCode2": "CREL2960"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "BG"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2960
