"MethodCountryRelCode2": "CREL2945"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "LU"
"MethodCountryRelMethodId": "SHIP6"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2945
