"MethodCountryRelCode2": "CREL2444"
"MethodCountryRelMethodType": "TAXSETTING"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "MA"
"MethodCountryRelAutoId": 2444
