"MethodCountryRelCode2": "CREL2957"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "DK"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2957
