"MethodCountryRelCode2": "CREL111"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "SI"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3087
