"MethodCountryRelCode2": "CREL139"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "MO"
"MethodCountryRelAutoId": 3115
