"MethodCountryRelCode2": "CREL83"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "CA"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "NT"
"MethodCountryRelAutoId": 3059
