"MethodCountryRelCode2": "CREL112"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "ES"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3088
