"MethodCountryRelCode2": "CREL100"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "IT"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3076
