"MethodCountryRelCode2": "CREL123"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "FL"
"MethodCountryRelAutoId": 3099
