"MethodCountryRelCode2": "CREL2439"
"MethodCountryRelMethodType": "TAXSETTING"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "IL"
"MethodCountryRelAutoId": 2439
