"MethodCountryRelCode2": "CREL2965"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "EE"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2965
