"MethodCountryRelCode2": "CREL70"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "ES"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3046
