"MethodCountryRelCode2": "CREL87"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "CA"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "PE"
"MethodCountryRelAutoId": 3063
