"MethodCountryRelCode2": "CREL2970"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "HU"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2970
