"MethodCountryRelCode2": "CREL116"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "AZ"
"MethodCountryRelAutoId": 3092
