"MethodCountryRelCode2": "CREL2930"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "CA"
"MethodCountryRelMethodId": "SHIP6"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2930
