"MethodCountryRelCode2": "CREL2968"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "DE"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2968
