"MethodCountryRelCode2": "CREL2786"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "DE"
"MethodCountryRelMethodId": "SHIP3"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2786
