"MethodCountryRelCode2": "CREL52"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "FR"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3028
