"MethodCountryRelCode2": "CREL165"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "WY"
"MethodCountryRelAutoId": 3141
