"MethodCountryRelCode2": "CREL2949"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "PL"
"MethodCountryRelMethodId": "SHIP6"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2949
