"MethodCountryRelCode2": "CREL57"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "IT"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3033
