"MethodCountryRelCode2": "CREL2979"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "NO"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2979
