"MethodCountryRelCode2": "CREL2961"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "CA"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2961
