"MethodCountryRelCode2": "CREL140"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "MT"
"MethodCountryRelAutoId": 3116
