"MethodCountryRelCode2": "CREL59"
"MethodCountryRelMethodType": "SHIP"
"MethodCountryRelCountryId": "LV"
"MethodCountryRelMethodId": "SHIP5"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3035
