"MethodCountryRelCode2": "CREL2476"
"MethodCountryRelMethodType": "TAXSETTING"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "WY"
"MethodCountryRelAutoId": 2476
