"MethodCountryRelCode2": "CREL39"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "DK"
"MethodCountryRelMethodId": "PAY1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 3011
