"MethodCountryRelCode2": "CREL2980"
"MethodCountryRelMethodType": "PAY"
"MethodCountryRelCountryId": "PL"
"MethodCountryRelMethodId": "PAY2"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": true
"MethodCountryRelRegionCode": ""
"MethodCountryRelAutoId": 2980
