"MethodCountryRelCode2": "CREL2454"
"MethodCountryRelMethodType": "TAXSETTING"
"MethodCountryRelCountryId": "US"
"MethodCountryRelMethodId": "1"
"MethodCountryRelLanguageId": ""
"MethodCountryRelIsDefault": false
"MethodCountryRelRegionCode": "NE"
"MethodCountryRelAutoId": 2454
