"paragraphUniqueId": f548525a-f15d-4650-aa87-bbb7a864628a
"sourceParagraphId": 125
"sortOrder": 19
"itemType": "Swift-v2_Text"
"header": "Frequently asked questions"
"template": ""
"colorSchemeId": "light"
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "52cb5376-fddd-48fa-9b65-6e345bec1fd0"
  "Id": "25"
  "ItemInstanceType": ""
  "Sort": 0
  "Subtitle": ""
  "Text": ""
  "Title": "<h3 class=\"dw-h4\">Our Management</h3>"
"columnId": 1
