"paragraphUniqueId": 48b467ae-b053-40b7-8cf2-37821c334ead
"sourceParagraphId": 21823
"sortOrder": 15
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "7afd5939-fbe1-4d71-8b81-5f9db7e59cb3"
  "Height": "32"
  "Id": "705"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
