"paragraphUniqueId": c4a64663-3ad1-423c-b061-07b42d8bd158
"sourceParagraphId": 151
"sortOrder": 2
"itemType": "Swift-v2_Text"
"header": "Search results"
"template": "TextLeft.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "5f234b61-667a-4fa7-956b-00183e182dab"
  "Id": "33"
  "ItemInstanceType": ""
  "Sort": 0
  "Subtitle": ""
  "Text": ""
  "Title": "<h2 class=\"dw-h3\">Search results</h2>"
"columnId": 1
