"paragraphUniqueId": c76eb3ce-603c-4142-aff6-d4f4f3a4e68c
"sourceParagraphId": 7301
"sortOrder": 1
"itemType": "Swift-v2_EmailHeading"
"header": "Do not miss out. It is your last change to shop these special offers"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "32"
  "GlobalRecordPageGuid": "4081a661-c987-4804-897d-5a1a6b500f10"
  "Id": "19"
  "ItemInstanceType": ""
  "LineHeight": "1.25"
  "Padding": "0"
  "Sort": 0
  "Title": "Do not miss out. It is your last change to shop these special offers"
"columnId": 1
