"id": fd155a00-1192-4429-9cb2-bcd219b0314d
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 3
"topSpacing": 0
"bottomSpacing": 6
"verticalAlignment": "None"
"fields":
  "Id": "949"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
