"paragraphUniqueId": 69bb2430-87ff-4a40-84a9-79ef2bae7eee
"sourceParagraphId": 21825
"sortOrder": 17
"itemType": "Swift-v2_EmailHeading"
"header": "By Dynamicweb"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "12"
  "GlobalRecordPageGuid": "7afd5939-fbe1-4d71-8b81-5f9db7e59cb3"
  "Id": "414"
  "ItemInstanceType": ""
  "LineHeight": "1.5"
  "Padding": "0"
  "Sort": 0
  "Title": "By Dynamicweb"
"columnId": 1
