"paragraphUniqueId": 5fbfc8a8-8f90-4424-a64a-4bd2a07df4f2
"sourceParagraphId": 171
"sortOrder": 1
"itemType": "Swift-v2_Feature"
"header": "Confirmed"
"template": "IconBoxTop.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "9b1d368a-3483-422f-b3ab-958e40ae8c28"
  "Icon": "/Files/Images/Icons/check.svg"
  "Id": "11"
  "ItemInstanceType": ""
  "Sort": 0
  "Text": "<p class=\"dw-paragraph\">Thank you for creating the user profile. Please check your email.</p><p></p>"
  "Title": "<p class=\"dw-paragraph-1\">Confirmed</p>"
"columnId": 1
