"paragraphUniqueId": 317aa40d-f260-4cd5-a1b1-a1c379f0c247
"sourceParagraphId": 21905
"sortOrder": 52
"itemType": "Swift-v2_EmailSpacer"
"header": "24"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "29d6b442-6011-4315-9d5c-326759221023"
  "Height": "24"
  "Id": "757"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
