"paragraphUniqueId": b6585254-b1c3-4f04-a14e-530ca2daf5da
"sourceParagraphId": 21980
"sortOrder": 16
"itemType": "Swift-v2_EmailHeading"
"header": "Swift"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "32"
  "GlobalRecordPageGuid": "14ba3ff7-6f6f-45a1-b178-d8fec858c859"
  "Id": "444"
  "ItemInstanceType": ""
  "LineHeight": "1.5"
  "Padding": "0"
  "Sort": 0
  "Title": "Swift"
"columnId": 1
