"paragraphUniqueId": 688614f5-8fd4-4a08-b134-a336536a1f20
"sourceParagraphId": 6831
"sortOrder": 4
"itemType": "Swift-v2_Poster"
"header": "Lost Lake starts at its namesake trailhead."
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "4f3d48a7-8635-48a7-8d48-660bbfbe4678"
  "Id": "356"
  "Image": ""
  "ItemInstanceType": ""
  "Sort": 0
  "Text": "This ridge is more rugged than the other two ridges. Freeze-thaw cycle isn't awful, but does make this trail rather slick. A trail & parking area reconstruction project completed in July '17. It is typically maintained at a high level due to its popularity and use. More branches down and seems they are often in bad spots, i.e. landings. A steep, punchy switchback filled climb follows a set of spines from Ridgecrest Conference Center in Black Mountain, NC to the parking lot of Old Fort Picnic area.\r\n"
  "Title": "Lost Lake starts at its namesake trailhead. "
"columnId": 2
