"paragraphUniqueId": 5d6e4559-a139-4c76-891a-d93d1c87bbdf
"sourceParagraphId": 21846
"sortOrder": 9
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "d64e3ca2-b3f8-43c6-af45-165daad9e16b"
  "Height": "32"
  "Id": "716"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
