"id": 477864a9-0984-47d6-954d-72ae7c5e6b20
"sortOrder": 3
"definitionId": "1ColumnFlex"
"itemType": "Swift-v2_RowFlex"
"container": "Grid"
"containerWidth": 2
"topSpacing": 1
"bottomSpacing": 1
"verticalAlignment": "None"
"fields":
  "Id": "22"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
