"pageUniqueId": 792cead9-787d-40ed-8650-6948d1b87ef2
"sourcePageId": 89
"name": "Customer center"
"menuText": "Customer center"
"sortOrder": 2
"isActive": true
"itemType": "Swift-v2_Page"
"layoutApplyToSubPages": false
"isFolder": false
"isTemplate": false
"isStructuralStub": false
"hidden": false
"allowclick": false
"allowsearch": true
"showInSitemap": true
"showInLegend": true
"sslMode": 0
"displayMode": "Normal"
"activeFrom": 2025-12-11T09:17:00.0000000
"activeTo": 2999-12-31T23:59:59.0000000
"permissionType": 2
"masterPageGuid": 268d7a76-1087-41c5-858e-b38c9a867cb1
"masterType": "None"
"seo":
  "noindex": false
  "nofollow": false
  "robots404": false
"urlSettings":
  "urlIgnoreForChildren": false
  "urlUseAsWritten": false
"visibility":
  "hideForPhones": false
  "hideForTablets": false
  "hideForDesktops": false
"fields":
  "Id": "54"
  "ItemInstanceType": ""
  "Sort": 2
  "Title": "Customer center"
"propertyFields":
  "Id": "89"
  "Sort": 0
  "ItemInstanceType": ""
  "SubmenuType": "auto"
