"paragraphUniqueId": 710f2428-8676-42cd-8cc8-3c0ab91ea90e
"sourceParagraphId": 144
"sortOrder": 8
"itemType": "Swift-v2_ProductFieldDisplayGroupsAccordion"
"header": "(EMPTY)"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "CustomizeLayouts": false
  "FieldDisplayGroupLayoutSelector": 0
  "FieldDisplayGroups": "[\"MainFeatures\",\"All_specs\",\"Engine\",\"Battery\",\"Equipment\",\"Bike_spec\",\"Clothing_spec\",\"Short_clothes_info\"]"
  "GlobalRecordPageGuid": "f100774e-2061-484d-aa59-6050df9fc539"
  "HideFieldLabels": false
  "HideFieldsWithZeroValue": false
  "HideTitle": false
  "Id": "2"
  "ItemInstanceType": ""
  "Layout": "bullets"
  "Sort": 0
  "Title": ""
  "TitleFontSize": "h5"
"columnId": 1
