"id": 66e5a691-5e18-40e9-8315-ebf45b2d2613
"sortOrder": 1
"definitionId": "4ColumnsFlex"
"itemType": "Swift-v2_RowFlex"
"container": "Grid"
"containerWidth": 2
"colorSchemeId": "dark"
"topSpacing": 6
"bottomSpacing": 4
"gapX": 3
"gapY": 3
"mobileLayout": "12,12,12,12"
"verticalAlignment": "Start"
"flexibleColumns": "0,0,0,0"
"fields":
  "Id": "59"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
- "id": 2
  "width": 0
- "id": 3
  "width": 0
- "id": 4
  "width": 0
