"id": 6e3fcd02-3227-4826-8277-0789a4fd4306
"sortOrder": 5
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"topSpacing": 0
"bottomSpacing": 5
"verticalAlignment": "None"
"columns":
- "id": 1
  "width": 0
