"id": c4157b7f-e089-48a8-b920-d3a678c03637
"sortOrder": 5
"definitionId": "1ColumnEmail"
"itemType": "Swift-v2_EmailRow"
"container": "Grid"
"colorSchemeId": "dark"
"verticalAlignment": "None"
"fields":
  "Id": "288"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
