"paragraphUniqueId": 4bdb006d-e6ef-4e6b-b229-48e214f131c5
"sourceParagraphId": 2774
"sortOrder": 2
"itemType": "Swift-v2_Text"
"header": "Text"
"template": "TextLeft.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "d88f09e2-1a31-48df-9d76-6596282a1f1c"
  "Id": "208"
  "ItemInstanceType": ""
  "Sort": 0
  "Subtitle": ""
  "Text": "<p class=\"dw-paragraph\">Our normal delivery time is 2-5 days (mon-fri). You will get an confirmation email when you make an order. When the package is leaving the warehouse, you will be able to track it, using the provided tracking number.</p><p class=\"dw-paragraph\">You can always see the status of your orders, by logging in to the customer center: <br></p>"
  "Title": ""
"columnId": 1
