"id": b74b5322-7e65-4e4c-b0a6-e83594887266
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"topSpacing": 0
"bottomSpacing": 0
"verticalAlignment": "None"
"fields":
  "Id": "503"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
