"paragraphUniqueId": b449983d-7d77-49c9-b6fc-cb1c1f5ac9f5
"sourceParagraphId": 22146
"sortOrder": 9
"itemType": "Swift-v2_Feature"
"header": "Dedicated account support"
"template": "IconLeft.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Button": "{\r\n  \"SelectedValue\": \"\",\r\n  \"Label\": \"\",\r\n  \"Link\": \"\",\r\n  \"LinkType\": \"\",\r\n  \"Style\": \"outline-primary\"\r\n}"
  "GlobalRecordPageGuid": "5c47a52a-4a24-449e-8df9-563f03afe297"
  "Icon": "/Files/Images/Icons/house.svg"
  "Id": "1667"
  "ItemInstanceType": ""
  "Sort": 0
  "Text": "<p>Whether it’s in our homes, our communities, or our daily routines, every small action we take adds up to a big change for our world.<br></p>"
  "Title": "<h3 class=\"dw-h6\">Dedicated account support</h3>"
"columnId": 3
