"paragraphUniqueId": 5de44f9f-c427-4c75-ac17-56a4e25cc3ed
"sourceParagraphId": 159
"sortOrder": 3
"itemType": "Swift-v2_BreadcrumbNavigation"
"header": "Breadcrumb navigation"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "781e72d3-f8f2-4927-bf6f-7764a4276ba6"
  "Id": "4"
  "ItemInstanceType": ""
  "ShowProductInBreadcrumb": true
  "Sort": 0
"columnId": 1
