"id": 05b160ab-7833-4edb-b876-2b8d8628c7d1
"sortOrder": 3
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 1
"topSpacing": 0
"bottomSpacing": 5
"verticalAlignment": "None"
"columns":
- "id": 1
  "width": 0
