"paragraphUniqueId": 8274d869-e14c-41a3-8d4a-39fc9328591a
"sourceParagraphId": 21899
"sortOrder": 46
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "29d6b442-6011-4315-9d5c-326759221023"
  "Height": "32"
  "Id": "753"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
