"CurrencyCode": "CZK"
"CurrencyLanguageId": "ESP"
"CurrencySymbol": "Kč"
"CurrencyName": "Czech Koruna"
"CurrencyRate": 29
"CurrencyIsDefault": false
"CurrencyCultureInfo": "cs-CZ"
"CurrencyPayGatewayCode": 203
"CurrencyRoundingId": ""
"CurrencySymbolPlace": 0
"CurrencyAutoId": 86
"CurrencyPositivePattern": 2
"CurrencyNegativePattern": -1
"CurrencyUseCurrencyCodeForFormat": false
