"CurrencyCode": "DKK"
"CurrencyLanguageId": "HRV"
"CurrencySymbol": "kr."
"CurrencyName": "Kroner"
"CurrencyRate": 15
"CurrencyIsDefault": false
"CurrencyCultureInfo": "da-DK"
"CurrencyPayGatewayCode": 208
"CurrencyRoundingId": ""
"CurrencySymbolPlace": 0
"CurrencyAutoId": 45
"CurrencyPositivePattern": 3
"CurrencyNegativePattern": 8
"CurrencyUseCurrencyCodeForFormat": false
