"CurrencyCode": "GBP"
"CurrencyLanguageId": "ITA"
"CurrencySymbol": "£"
"CurrencyName": "British Pound"
"CurrencyRate": 0
"CurrencyIsDefault": false
"CurrencyCultureInfo": "cy-GB"
"CurrencyPayGatewayCode": 0
"CurrencyRoundingId": ""
"CurrencySymbolPlace": 0
"CurrencyAutoId": 56
"CurrencyPositivePattern": 0
"CurrencyNegativePattern": 1
"CurrencyUseCurrencyCodeForFormat": false
