"CurrencyCode": "RON"
"CurrencyLanguageId": "ESP"
"CurrencySymbol": "RON"
"CurrencyName": "Leu"
"CurrencyRate": 150
"CurrencyIsDefault": false
"CurrencyCultureInfo": "ro-RO"
"CurrencyPayGatewayCode": 642
"CurrencyRoundingId": ""
"CurrencySymbolPlace": 0
"CurrencyAutoId": 162
"CurrencyPositivePattern": 3
"CurrencyNegativePattern": 8
"CurrencyUseCurrencyCodeForFormat": false
