"CurrencyCode": "USD"
"CurrencyLanguageId": "NON"
"CurrencySymbol": "$"
"CurrencyName": "US Dollar"
"CurrencyRate": 1
"CurrencyIsDefault": false
"CurrencyCultureInfo": "en-US"
"CurrencyPayGatewayCode": 0
"CurrencyRoundingId": 
"CurrencySymbolPlace": 0
"CurrencyAutoId": 75
"CurrencyPositivePattern": 0
"CurrencyNegativePattern": 1
"CurrencyUseCurrencyCodeForFormat": false
