"paragraphUniqueId": 7242c550-3cec-42e1-b614-23da52fa9127
"sourceParagraphId": 21843
"sortOrder": 6
"itemType": "Swift-v2_EmailSpacer"
"header": "32"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "d64e3ca2-b3f8-43c6-af45-165daad9e16b"
  "Height": "32"
  "Id": "715"
  "ItemInstanceType": ""
  "Sort": 0
"columnId": 1
