"id": 81999b9b-8095-4faf-b116-da9c832ecd80
"sortOrder": 30
"definitionId": "1ColumnEmail"
"itemType": "Swift-v2_EmailRow"
"container": "Grid"
"colorSchemeId": "dark"
"verticalAlignment": "None"
"fields":
  "Id": "502"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
