"id": fc7dab77-996d-47ba-af1d-90f694048316
"sortOrder": 1
"definitionId": "1ColumnFlex"
"itemType": "Swift-v2_RowFlex"
"container": "Grid"
"topSpacing": 0
"bottomSpacing": 0
"verticalAlignment": "None"
"fields":
  "Id": "4"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
