"id": 5d4c5b85-8190-49d5-b4b8-cbad2ecf7889
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"containerWidth": 3
"topSpacing": 0
"bottomSpacing": 6
"verticalAlignment": "None"
"fields":
  "Id": "88"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
