"paragraphUniqueId": 91a1415c-3427-4fac-8282-d0039b379b76
"sourceParagraphId": 107
"sortOrder": 1
"itemType": "Swift-v2_App"
"header": "Quotes"
"template": ""
"colorSchemeId": ""
"moduleSystemName": "eCom_CustomerExperienceCenter"
"moduleSettings": |-
  <?xml version="1.0" encoding="utf-8"?>
  <Settings>
    <OrderType>Quote</OrderType>
    <RetrieveListBasedOn>UseUserID</RetrieveListBasedOn>
    <PageSize>10</PageSize>
    <SortByField>CreatedAt</SortByField>
    <SortOrder>Desc</SortOrder>
    <OrderListTemplate>Quotes_List.cshtml</OrderListTemplate>
    <DetailTemplate>Quotes_Details.cshtml</DetailTemplate>
    <EmailTemplate></EmailTemplate>
    <LedgerType></LedgerType>
    <LedgerFlowStates></LedgerFlowStates>
  </Settings>
"fields":
  "GlobalRecordPageGuid": "1ccf14da-0fd6-4f46-8ad4-d9410e0a11ea"
  "Id": "44"
  "ItemInstanceType": ""
  "Sort": 0
  "Title": "Quotes"
"columnId": 1
