"paragraphUniqueId": cd2c870d-316d-4765-8bb3-f10330e0edfd
"sourceParagraphId": 21832
"sortOrder": 33
"itemType": "Swift-v2_EmailHeading"
"header": "Swift"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "40"
  "GlobalRecordPageGuid": "29d6b442-6011-4315-9d5c-326759221023"
  "Id": "415"
  "ItemInstanceType": ""
  "LineHeight": "1.5"
  "Padding": "0"
  "Sort": 0
  "Title": "Swift"
"columnId": 1
