"paragraphUniqueId": fbc3d4eb-94d0-4e3a-9f4a-d78017279e72
"sourceParagraphId": 9759
"sortOrder": 2
"itemType": "Swift-v2_EmailHeading"
"header": "Thank you"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "Align": "center"
  "BorderThicknes": "1"
  "Borders": "none"
  "FontSize": "32"
  "GlobalRecordPageGuid": "a65aa8c9-49a7-4013-94a3-751eef5aafa3"
  "Id": "157"
  "ItemInstanceType": ""
  "LineHeight": "1.5"
  "Padding": "8"
  "Sort": 0
  "Title": "Thank you"
"columnId": 1
