"id": 2b281fad-45b0-471a-b617-5de4ae6d4d5e
"sortOrder": 4
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"topSpacing": 3
"bottomSpacing": 3
"verticalAlignment": "None"
"fields":
  "Id": "93"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
