"paragraphUniqueId": e063b6ba-98e4-4369-aaa5-8c83e2a57f1e
"sourceParagraphId": 112
"sortOrder": 4
"itemType": "Swift-v2_Text"
"header": "(EMPTY)"
"template": "TextLeft.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "2ddf8daf-2ae0-4eb3-9d4b-268e195342d6"
  "Id": "22"
  "ItemInstanceType": ""
  "Sort": 0
  "Subtitle": "<p class=\"dw-paragraph-1\">Welcome back, you are logged in as a CSR</p>"
  "Text": "<p class=\"dw-paragraph\">Get an overview over your Accounts and users. Impersonate a user to help them with their invoices, issues or follow up on their carts and orders<br></p><p></p>"
  "Title": ""
"columnId": 1
