"paragraphUniqueId": ef57207a-6f11-4b4d-aaab-082e1e620cec
"sourceParagraphId": 175
"sortOrder": 2
"itemType": "Swift-v2_Text"
"header": "Sign in"
"template": "TextCenter.cshtml"
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "37f77e12-1947-4dd2-89ae-8319697016a4"
  "Id": "38"
  "ItemInstanceType": ""
  "Sort": 0
  "Subtitle": ""
  "Text": "<div>Don&#39;t have a user profile yet? <a href=\"Default.aspx?ID=136\">Create user profile here</a></div><div></div><p></p>"
  "Title": "<h2 class=\"dw-h2\">Sign in</h2>"
"columnId": 1
