"ShopId": "SHOP14"
"ShopName": "Channel - Amazon"
"ShopDefault": false
"ShopIcon": ""
"ShopOrderFlowId": 
"ShopStockStateId": "STOCKGRP1"
"ShopOrderContextId": ""
"ShopStockLocationID": 1
"ShopDefaultPrintTemplate": ""
"ShopUseAlternativeImages": false
"ShopImageFolder": ""
"ShopImagePatternSmall": ""
"ShopImagePatternMedium": ""
"ShopImagePatternLarge": ""
"ShopAlternativeImagePatterns": 
"ShopProductWarehouse": false
"ShopProductPrimaryPageId": 
"ShopAutoBuildIndex": true
"ShopIndexRepository": "ProductsBackend"
"ShopIndexName": "Products.index"
"ShopImageSearchInSubFolders": false
"ShopImageUploadFolder": 
"ShopAutoCreateUploadFolderPerProduct": false
"ShopType": 3
"ShopCompletionRules": ""
"ShopCompletionLanguageIds": ""
"ShopImagePatternMain": ""
"ShopImagePatternVariant": ""
