"ShopId": "SHOP9"
"ShopName": "Digital Assets Portal"
"ShopDefault": false
"ShopIcon": ""
"ShopOrderFlowId": 
"ShopStockStateId": ""
"ShopOrderContextId": ""
"ShopStockLocationID": 0
"ShopDefaultPrintTemplate": ""
"ShopUseAlternativeImages": false
"ShopImageFolder": "/"
"ShopImagePatternSmall": ""
"ShopImagePatternMedium": ""
"ShopImagePatternLarge": ""
"ShopAlternativeImagePatterns": "[]"
"ShopProductWarehouse": false
"ShopProductPrimaryPageId": 
"ShopAutoBuildIndex": true
"ShopIndexRepository": "ProductsBackend"
"ShopIndexName": "Products.index"
"ShopImageSearchInSubFolders": false
"ShopImageUploadFolder": 
"ShopAutoCreateUploadFolderPerProduct": false
"ShopType": 3
"ShopCompletionRules": ""
"ShopCompletionLanguageIds": ""
"ShopImagePatternMain": "/{ProductNumber}{VariantOptionLevel1}.jpg"
"ShopImagePatternVariant": "/{ProductNumber}{VariantOptionLevel1}.jpg"
