"paragraphUniqueId": f2be496a-efbf-4495-b584-48a85493eb5c
"sourceParagraphId": 20186
"sortOrder": 8
"itemType": "Swift-v2_ProductListNavigation"
"header": "T"
"template": ""
"colorSchemeId": ""
"moduleSystemName": ""
"moduleSettings": ""
"fields":
  "GlobalRecordPageGuid": "39a2ca01-0400-4ff2-9213-7f5c942da6ed"
  "GroupNavigationLayout": "filter"
  "GroupNavigationStartLevel": "1"
  "GroupNavigationStopLevel": "9"
  "Id": "7"
  "ItemInstanceType": ""
  "Sort": 0
  "Title": ""
"columnId": 1
