"id": 3f304fd3-564e-4f0d-b008-0a2c415cbcb2
"sortOrder": 2
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"verticalAlignment": "None"
"fields":
  "Id": "26"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
