"id": 5ad227fe-e7e2-4fbc-982a-1fb9e7d7536e
"sortOrder": 1
"definitionId": "1Column"
"itemType": "Swift-v2_Row"
"container": "Grid"
"topSpacing": 1
"bottomSpacing": 3
"verticalAlignment": "None"
"fields":
  "Id": "90"
  "Sort": 0
  "ItemInstanceType": ""
"columns":
- "id": 1
  "width": 0
